server:
  max-http-header-size: 48000
  port: 8080
  servlet:
    context-path: /api
    # session:
      # cookie:
        # same-site: none
        # secure: true

spring:
  application:
    name: application-ws
  profiles:
    active: default
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
        use_jdbc_metadata_defaults: false
      properties:
        hibernate:
          hbm2ddl:
            auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:postgresql://tveste-db.cbiuawxnssk1.us-east-1.rds.amazonaws.com:5432/tveste
    driverClassName: org.postgresql.Driver
    username: 'tveste'
    password: 'tveste#admin'
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      springframework:
        security: DEBUG