server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: none
        secure: true

spring:
  application:
    name: application-ws
  profiles:
    active: default
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.SQLServerDialect
      temp:
        use_jdbc_metadata_defaults: false
  #    properties:
  #      hibernate:
  #        hbm2ddl:
  #          auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:sqlserver://tveste-db.database.windows.net;database=tveste-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: 'tveste-db'
    password: '#grupo05'
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      springframework:
        security: DEBUG